# ActionMailer configuration
# Mailer settings
mailer:
  smtp_settings:
    address: 'smtp.gmail.com'
    port: '587'
    domain: 'gmail.com'
    user_name: 'red.legislativa@gmail.com'
    password: 'los_pueblos_siempre_insurgimos'
    authentication: 'plain'
    enable_starttls_auto: true


registration_mailer:
  from_header: 'red.legislativa@gmail.com'


version: development
debug_mode: true

