# ActionMailer configuration
# Mailer settings
mailer:
  smtp_settings:
    address: 'smtp.gmail.com'
    port: '587'
    domain: 'gmail.com'
    user_name: 'red.legislativa@gmail.com'
    password: 'los_pueblos_insurgen'
    authentication: 'plain'
    enable_starttls_auto: true


registration_mailer:
  from_header: 'red.legislativa@gmail.com'


elasticsearch:
  client:
    url: localhost:9200
  default_settings:
    index_name: project_index
    document_type: project_index
    index:
      analysis:
        filter:
          es_stopwords:
            type: stop
            stopwords: '_spanish_'

version: development
debug_mode: true

