# ActionMailer configuration
# Mailer settings
mailer:
  smtp_settings:
    address: 'smtp.gmail.com'
    port: '587'
    domain: 'gmail.com'
    user_name: 'maira.diaz.73@gmail.com'
    password: 'patrialibrejustaysoberana'
    authentication: 'plain'
    enable_starttls_auto: true


registration_mailer:
  from_header: 'maira.diaz.73@gmail.com'
