#Maiiler settings
mailer:
  smtp_settings:
    address: 'smtp.gmail.com'
    port: 587
    domain: 'gmail.com'
    user_name: 'red.legislativa@gmail.com'
    password: 'los_pueblos_insurgen'
    authentication: 'plain'
    enable_starttls_auto: true
